apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rok
spec:
  rules:
  - host: rok.chilling.dev
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rok
            port:
              number: 3000
