apiVersion: v1
kind: PersistentVolume
metadata:
  name: rok-db-pv
  labels:
    app: rok-db
spec:
  storageClassName: fast-service-db
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
